version: '2'
services:
    bench-app:
        image: bench
        external_links:
            - bench-mysql:mysql
            - bench-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bench?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    bench-mysql:
        extends:
            file: mysql.yml
            service: bench-mysql
    bench-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: bench-elasticsearch
